name: DISRUPTIONLAB
favicon: null
layout_spectrum: 0.8164887842722237
typography_spectrum: 0.58934
title: 'AD AGENCY RESEARCH & DEVELOPMENT'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#999999'
    - '#6a6a6a'
    - '#414141'
  brandStrength: 0.1875
  lightness: 0.39328929828479886
  saturation: 0.4657511869445443
  rhythmicContrast: 0.6501147516537458
purpose: []
