title: 'AD AGENCY RESEARCH & DEVELOPMENT'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5250896
  brandStrength: 0.4408602
  lightness: 0.3932893
  brandColors:
    - '#E0DED9'
    - '#3B3A37'
  rhythmicContrast: 0.6501148
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: DISRUPTIONLAB
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0
layout_spectrum: 0.4677419
