name: DISRUPTIONLAB
favicon: null
layout_spectrum: 0.17911
typography_spectrum: 0.58934
title: 'AD AGENCY RESEARCH & DEVELOPMENT'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#999999'
    - '#6a6a6a'
    - '#414141'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
